// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.UserService.Data;

#nullable disable

namespace TaskManagement.UserService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260325124233_InitialCreate")]
    partial class InitialCreate
    {
    }
}
