// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.TaskService.Data;

#nullable disable

namespace TaskManagement.TaskService.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20260325124233_InitialCreate")]
    partial class InitialCreate
    {
    }
}
